const mongoose=require("mongoose")
const infoSchema=mongoose.Schema({
    fname:{
        type:String,
        required:true,
        trim:true
    },
    lname:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    pass:{
        type:String,
        required:true,
        trim:true
    },
    cpass:{
        type:String,
        required:true,
        trim:true
    },
    mobile:{
        type:String,
        required:true,
        trim:true
    },
    dob:{
        type:String,
        required:true,
        trim:true
    },
    gender:{
        type:String,
        required:true,
        trim:true
    },
    list:{
        type:String,
        required:true,
        trim:true
    },
    addrs:{
        type:String,
        required:true,
        trim:true
    },
    createdTime:{
        type:Date,
        default:Date.now
    }
})
infoSchema.path('email')
module.exports=mongoose.model("info",infoSchema);